2019-06-02 08:47:12,070 : kivy : Factory: 194 symbols loaded
2019-06-02 08:47:12,356 : kivy : Image: Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
2019-06-02 08:47:12,441 : kivy : VideoGstplayer: Using Gstreamer 1.10.4.0
2019-06-02 08:47:12,442 : kivy : Video: Provider: gstplayer
2019-06-02 08:47:12,535 : kivy : Loading MPF-MC controller
2019-06-02 08:47:12,535 : mpfmc : Mission Pinball Framework Media Controller v0.52.2
2019-06-02 08:47:12,537 : mpfmc : Mission Pinball Framework Game Engine v0.52.2
2019-06-02 08:47:12,537 : mpfmc : Machine path: /home/murray/pinball/machines/test
2019-06-02 08:47:12,538 : ConfigProcessor : Cache file not found: /tmp/75a098f7a80ab927cf616400276deb57.mpf_cache
2019-06-02 08:47:12,538 : ConfigProcessor : Loading config from file /usr/local/lib/python3.5/dist-packages/mpfmc/mcconfig.yaml.
2019-06-02 08:47:12,700 : ConfigProcessor : Loading config: /usr/local/lib/python3.5/dist-packages/mpfmc/mcconfig.yaml
2019-06-02 08:47:12,751 : ConfigProcessor : Loading config from file /home/murray/pinball/machines/test/config/config.
2019-06-02 08:47:12,775 : ConfigProcessor : Loading config: /home/murray/pinball/machines/test/config/config
2019-06-02 08:47:12,776 : kivy : Could not find file /home/murray/pinball/machines/test/config/machine-config.yaml
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/mpf/core/file_manager.py", line 80, in load
    file = FileManager.locate_file(filename)
  File "/usr/local/lib/python3.5/dist-packages/mpf/core/file_manager.py", line 53, in locate_file
    raise FileNotFoundError("File not found: {}".format(filename))
FileNotFoundError: File not found: /home/murray/pinball/machines/test/config/machine-config.yaml

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/mpfmc/commands/mc.py", line 209, in __init__
    thread_stopper=thread_stopper).run()
  File "/usr/local/lib/python3.5/dist-packages/mpfmc/core/mc.py", line 97, in __init__
    self.machine_config = self._load_config()
  File "/usr/local/lib/python3.5/dist-packages/mpfmc/core/mc.py", line 223, in _load_config
    mpf_config = self.mpf_config_processor.load_config_files_with_cache(files, "machine", True)
  File "/usr/local/lib/python3.5/dist-packages/mpf/core/config_processor.py", line 112, in load_config_files_with_cache
    ignore_unknown_sections)
  File "/usr/local/lib/python3.5/dist-packages/mpf/core/config_processor.py", line 163, in _load_config_file_and_return_loaded_files
    subconfig, subsubfiles = self._load_config_file_and_return_loaded_files(full_file, config_type)
  File "/usr/local/lib/python3.5/dist-packages/mpf/core/config_processor.py", line 132, in _load_config_file_and_return_loaded_files
    config = FileManager.load(filename, expected_version_str, True)
  File "/usr/local/lib/python3.5/dist-packages/mpf/core/file_manager.py", line 83, in load
    raise IOError("Could not find file {}".format(filename))
OSError: Could not find file /home/murray/pinball/machines/test/config/machine-config.yaml
2019-06-02 08:47:12,777 : kivy : Stopping child threads... (0 remaining)
2019-06-02 08:47:12,778 : kivy : All child threads stopped.
